'''Constants setting the global parameters of TrueSkill.'''
DEFAULT_MEAN = 25
DEFAULT_STD_DEV = DEFAULT_MEAN / 3
DEFAULT_VARIANCE = DEFAULT_STD_DEV ** 2

SKILL_CLASS_WIDTH = (DEFAULT_STD_DEV / 2) ** 2
DRAW_PROBABILITY = 0.01  # 1 percent
ADDITIVE_DYNAMICS_FACTOR = (DEFAULT_STD_DEV / 100) ** 2
TOLERANCE = 1e-18
